name: pixie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_floating_bottom_bar: ^1.2.1+1
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  google_nav_bar: ^5.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  line_icons: ^2.0.3
  lottie: ^3.2.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  wallpaper_manager_plus: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_launcher_icons:
  android: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_background: "assets/images/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: space
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf

    - family: spaceMedium
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf

    - family: spaceSemiBold
      fonts:
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf

    - family: spaceBold
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
        
    - family: sellena
      fonts:
        - asset: assets/fonts/SellenaBrush.ttf
    - family: anything
      fonts:
        - asset: assets/fonts/Anything.otf
    - family: quagera
      fonts:
        - asset: assets/fonts/QuageraRegular.otf
    - family: yesterday
      fonts:
        - asset: assets/fonts/Yesterday.otf
    - family: sfArabic
      fonts:
        - asset: assets/fonts/SF-Arabic.ttf
  
  assets:
    - assets/animations/
    - assets/images/
    - assets/images/categories/
    - assets/images/colors/
    - assets/images/svgs/
    - .env