name: pixie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.2.1+1
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: space
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf

    - family: spaceMedium
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf

    - family: spaceSemiBold
      fonts:
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf

    - family: spaceBold
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf